spring.application.name=${SPRING_APPLICATION_NAME:Ecomove}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
server.port=${SERVER_PORT:8080}
GEOCODE_USER_AGENT_EMAIL=${GEOCODE_USER_AGENT_EMAIL}
stripe.secret.key=${STRIPE_SECRET_KEY}  

dejo este correo para que puedas ejecutar local mientras y la api geocode no de problemas